name: Selenium Cucumber BDD Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for faster builds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Change to your Java version (8, 11, 15, etc.)

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome Version: $CHROME_VERSION"
          sudo apt-get install -y chromium-chromedriver

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Tests with Maven (Update Command if Needed)
        run: mvn clean test -Dcucumber.options="--tags @Regression"  # Change tags as needed
